### ISSUE TITLE
Nested lists in sidebar navigation

### ISSUE THREAD

**Issue by mrmartineau** [pedronauck/docz#10]
Is it possible to have nested lists in the sidebar navigation? I am using the `route` front-matter and I would like the navigation to follow the hierarchy of my files.

e.g.

```
- Components
  - Atoms
    - Buttons
    - Heading
  - Molecules
	- Masthead
```

**Comment by Swapnull** [comment]
It is already possible to have a single nested item using the `menu` front-matter item. 

I have started working on a spin on the basic theme that will allow you to define deeper menu items with the `menu` option by doing something like `menu: level1/level2/level3`, so in your case
`menu: Components/Atoms` and `menu: Components/Molecules`

If you want to then change it to use the `route` rather than `menu`, that should easy enough. 

I have ran out of time on this tonight, so will revisit tomorrow :)

**Comment by mrmartineau** [comment]
I hadn't seen the `menu` front-matter item. It may be good enough for our needs in the short-term. Thanks

**Comment by giladgray** [comment]
@pedronauck I think this feature may have regressed with the recent changes to `menu`.

`menu: Components/Core` creates a new entry called "Components/Core"
![image](https://user-images.githubusercontent.com/464822/50367155-1aa4f500-0533-11e9-87f1-d54e3ec23e07.png)
