### ISSUE TITLE
Flow Type Example for Stateful React Components

### ISSUE THREAD

**Issue by chantlong** [pedronauck/docz#100]
## Question
I am able to use Flow Types with Stateless (Functional) React Components to displays Props using the `<PropsTable />` component, but it doesn't work for Stateful (Class) Components. Instead of using Flow Types, I have to use `prop-types` to get it to work.

When I mean, it doesn't work, I mean the PropsTable shows up empty on docz.
I do not get any errors as well on the build process nor console in docz

1. Is there an example on how Flow Types for Props can be used for Stateful Components?

2. How do I use the `Description` section for the `<PropsTable />`

```
types Props = {
  a: string
}

export default MyComponent extends Component<Props> {
...
}
```
↑ doesn't work.

Thank you.

**Comment by Swapnull** [comment]
@chantlong 
I am not sure this is a bug with Docz, as much as it is limitations of React Docgen. 

1) 
To get props table to show up, you need to do it as 
```js
type Props = { a: string }

class MyComponent extends Component<Props> { ... }

export default MyComponent;
```
I am assuming this is part of the React Docgen limitations mentioned in the PropTable section https://www.docz.site/introduction/documenting-your-things#built-in-components. 

2) 
As this uses React Docgen, you can set the description like so 

```js
type Props = { 
    /** This is my description of the prop type a :)  */
    a: string,
  /** This is my description of the prop type b :) */
    b: string 
}

```

I know it is fugly, but again, it is the limitation of React DocGen. 

Have a look at https://github.com/reactjs/react-docgen for the PropsTable stuff, there is flow based examples

**Comment by chantlong** [comment]
@Swapnull 

I have tried `1.` before but it didn't work. Thanks though! I'll stick with propTypes for the time being.
Noted on `2.`

**Comment by Swapnull** [comment]
Hey @chantlong, 
It would be good to know if this is actually a bug or a usage issue. 

I have just created a small flow example project with docz and a stateful Button component along the same vein as your that renders its proptypes just fine. https://github.com/Swapnull/docz-flow-example.

Only difference in the component is you are doing 
```js
export default MyComponent extends Component<Props> {
```
and I am doing
```js
export default class MyComponent extends Component<Props> {
```

I don't know if the `class` keyword is omittable from class exports, but my editor was complaining `[flow] Unexpected token extends` without it.

Are you able to fork this, confirm it works and add in your component to the project. If its still not working, upload the repo so we can check out the bug :) 
You could also just show us the repo that your issue is in if possible .

**Comment by chantlong** [comment]
@Swapnull Thank you for going through the trouble of making an example. I checked out the repo and compared the differences. 

I can confirm this isn't a bug now but a huge typo on my part. I passed `<Props>` to `MyComponent` like `export default class MyComponent<Props> extends Component {` instead. Interesting that React compiles fine with the typo. Please close the issue and I apologize for the false alarm.
