### ISSUE TITLE
order not applying correctly

### ISSUE THREAD

**Issue by mAAdhaTTah** [pedronauck/docz#110]
## Bug Report

**Describe the bug**

Using the `order` key in the `.mdx` file doesn't correctly reorder the menu items.

**To Reproduce**

1. Go to https://github.com/valtech-nyc/brookjs/pull/201
2. Clone the repository
3. Run `yarn && yarn docs:dev`
4. Open browser & verify menu order

**Expected behavior**

Menu should be reordered by `order` key.

**Enviroment**

* OS: OSX 10.13.5
* Node/npm version: Node 10.3.0/npm 6.1.0/yarn 1.7.0

**Additional context/Screenshots**

<img width="298" alt="brookjs" src="https://user-images.githubusercontent.com/4371429/42141199-8345b2d4-7d75-11e8-9070-ba2812602cda.png">

**Comment by Swapnull** [comment]
I think this is the same issue as raised in https://github.com/pedronauck/docz/issues/51

**Comment by mAAdhaTTah** [comment]
@Swapnull Appears similar, although that one was closed. Is it fixed?

It's also not entirely clear, looking at that issue & the docs, what `order` is supposed to do exactly. Do you know?

**Comment by Swapnull** [comment]
Ah, I think I see your issue looking again.

I think order is reversed to what you would think. if we were to have 100 pages, the one with `order: 100` would be at the top and the one with `order: 1` would be at the bottom. 

if we look at 
https://github.com/pedronauck/docz/blob/eb98beb969f9d21d35c95720a3691af08194105b/packages/docz/src/components/Docs.tsx#L54
It sorts by name and then order descending.
```
entriesArr
          .sort((a, b) => sortBy(a.name, b.name))
          .sort((a, b) => b.order - a.order)
```
Looking at this with a basic list, you get: 
```
> a = [100, 1 , 2, 74, 9]
[ 100, 1, 2, 74, 9 ]
> a.sort((a, b) => b - a)
[ 100, 74, 9, 2, 1 ]
```

So maybe the documentation needs to state its descending , or we need to change it so that it sorts upwards rather than downwards. What do you think @pedronauck?

**Comment by mAAdhaTTah** [comment]
Yeah... it def feels backwards that order 1, 2, 3 shows up as:

* 3
* 2
* 1

in the menu (hence me opening this issue in the first place).

**Comment by pedronauck** [comment]
For @Swapnull, the order in descending. I'll follow your guest and put it on the documentation!

**Comment by mAAdhaTTah** [comment]
This is fixed, so closing, although I do believe this should be the default behavior going forward.
