### ISSUE TITLE
How to use with with babel transform-class-properties plugin?

### ISSUE THREAD

**Issue by dmansurov83** [pedronauck/docz#114]
My .babelrc
```
{
  "plugins": ["transform-class-properties"]
}
```
But I have this error:
```
Module parse failed: Unexpected token (46:21)
You may need an appropriate loader to handle this file type.
| 
| export default class Button extends Component {
>     static propTypes = {
...
```

**Comment by pedronauck** [comment]
Try to use the [babel 7 version of this plugin](https://new.babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html)

**Comment by dmansurov83** [comment]
```
Module build failed (from ./node_modules/happypack/loader.js):
Error: [BABEL] /home/user/Workspace/frontend/docz/.docz/app/index.jsx: You gave us a visitor for the node type Priva
teName but it's not a valid type (While processing: "/home/user/Workspace/frontend/docz/node_modules/@babel/plugin-p
roposal-class-properties/lib/index.js")
    at verify (/home/user/Workspace/frontend/docz/node_modules/@babel/traverse/lib/visitors.js:143:13)
    at explode (/home/user/Workspace/frontend/docz/node_modules/@babel/traverse/lib/visitors.js:46:3)
    at Object.merge (/home/user/Workspace/frontend/docz/node_modules/@babel/traverse/lib/visitors.js:195:5)
    at _default (/home/user/Workspace/frontend/docz/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:163:61)
```

**Comment by dmansurov83** [comment]
My @babel/core had old version (7.0.0-beta.42 version).
I did add dev dependency "@babel/core": "^7.0.0-beta.51", but I still have error
```
Module parse failed: Unexpected token (46:21)
You may need an appropriate loader to handle this file type.
| 
| export default class Button extends Component {
>     static propTypes = {
```
Did .babelrc plugins applying to build .mdx?

**Comment by pedronauck** [comment]
For now, I'll close this issue in favor of the new release.

**Comment by jbcochery** [comment]
I ran into the same issue, it happens when you try to install docz in a subfolder, for example `/docz` and not at the project's root. I suppose this has something to do with [paths.root](https://github.com/pedronauck/docz/blob/436c742d37cd0f83c66504aaf99731ae6d173914/packages/docz-core/src/config/paths.ts#L17) being used as webpack's context [here](https://github.com/pedronauck/docz/blob/436c742d37cd0f83c66504aaf99731ae6d173914/packages/docz-core/src/bundlers/webpack/config.ts#L54) but I haven't investigated more than that.
