### ISSUE TITLE
Clarify "how to extend webpack"

### ISSUE THREAD

**Issue by bichotll** [pedronauck/docz#132]
## Current situation - my confusion

Hi there. I got a bit confused with the use of docz.
The fact is that I wanted to use my webpack file to transform css properties - I know there is a plugin for that.
I could not find in the docs how to do so.

## Suggestion

Is there any way we can give a better clarification in how webpack config can be extended?
We/docz users may need to extend it for many other things.

After checking the docs and the issues closed, I see there is an option to modify the bundler config. The issue is that it does not specify what exactly that does (it does not even mention webpack so I just kind of ignored that function).
https://www.docz.site/documentation/project-configuration#modifybundlerconfig
https://github.com/pedronauck/docz/issues/76

- Just a simple re-phrase of that
- (and) maybe a new section on the docs may help a lot :)
- Even a small link in the plugins page saying...missing a plugin? You may want to set it up yourself by configuring webpack?

## Possible action

I can create a few PRs for those. Let me know 👍

**Comment by pedronauck** [comment]
Really @bichotll I think that we can improve our documentation about that. Please, if you want to give us some help, you can send some PR on in the [docz-website](https://github.com/pedronauck/docz-website) repository.

I'll close this issue because I think that is related to the docz-website repository! ✌️
