### ISSUE TITLE
React-native support

### ISSUE THREAD

**Issue by telmen** [pedronauck/docz#16]
I'd like to know that If there'll be React Native support?
Thanks

**Comment by pedronauck** [comment]
Hy @telmen, to be honest, I'm very out of React native world. I think that this can be a really great feature to implement, but I don't have idea how!

**Comment by ygorlazaro** [comment]
It would be awesome, but me neither know how to implement such a thing. Perhaps someone from the react-native repository could help?

**Comment by albinekb** [comment]
I think it might be possible using https://github.com/necolas/react-native-web, but it will only work for pure-js components. Other than that there's probably no easy way to demo the component, except for streaming it from a real device like you can do in the expo playground 🤔

**Comment by mpaleo** [comment]
@albinekb That's a good approach, take a look at the [Storybook](https://github.com/storybooks/storybook/tree/master/app/react-native) solution.
The thing is the "native" part, this stuff depends a lot on the real device (or emulated) (sometimes). There are a lot of apps that use js-only components but others doesn't.
Again, i think that the Storybook approach it's not bad.
What do you think ?

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/roadmap/p/integration-with-react-native)
