### ISSUE TITLE
build just gives empty website

### ISSUE THREAD

**Issue by hayk94** [pedronauck/docz#199]
## Bug Report

**I open /dist/index.html and it's an empty page**

I build the docs with `docz build`

**To Reproduce**

1. Created a doczrc.json
```
{
  "src": "./mdDocs",
  "typescript": true,
  "themeConfig": {
    "mode": "dark"
  }
}

```
2. put a few mdx files in that folder
3. Run `docz dev`, server runs can see my documents
4. Run `docz build`, go to .docz/dist/index.html and it's and empty page

**Expected behavior**

Shouldn't I see in that index.html the same I see in the devserver?

**Environment**

* OS: Ubuntu 18.04.1
* Node/npm version: v10.7.0

**Comment by ilyanoskov** [comment]
could you check if there are any errors in developer console in the browser? may be the browser can't locate bundle.js files

**Comment by hayk94** [comment]
![image](https://user-images.githubusercontent.com/9801183/43782495-96c04bd6-9a70-11e8-9749-77c43144da74.png)
Yes here are the errors in the console.

**Comment by hayk94** [comment]
The issue is with `src`s.
It should be `./static/js/app.232bfeb18aca624e6cde.js` with dot in the beginning.

**Comment by ilyanoskov** [comment]
@hayk94 so this issue happens when there are conflicts with paths / relative paths. I assume you are not running the project through a static server, but rather just clicking on index.html. Try running the production build through nginx or `python -m SimpleHTTPServer` and see whether it works.

another solution would be to modify `base` option in `doczrc.js`. I had a similar issue and it solved it

**Comment by ilyanoskov** [comment]
@hayk94 as an alternative "quick and dirty" solution you can just open index.html and change paths for js files manually.

**Comment by hayk94** [comment]
Yes, just clicking index.html
What do you suggest to put for the `base`?
I usually have the same issue with srcs when deploying to github pages, so you might wanna check that as well.

**Comment by ilyanoskov** [comment]
@hayk94 for Github Pages to work I enabled hashRouter:true. You can see the whole `doczrc.js` file here: https://github.com/sumup/circuit-ui/blob/docz/doczrc.js

**Comment by pedronauck** [comment]
Thanks for the help @ilyanoskov, I'll close this issue in favor of your answer :v:

**Comment by jsargent-inmoment** [comment]
I know this issue is closed - but I can't see the `doczrc.js` link that @ilyanoskov posted.

 I'm getting the same problem - after the build I'm getting the error. The dev runs fine, but after I build it gives me this error.

`WebSocket connection to 'ws://127.0.0.1:60505/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`
