### ISSUE TITLE
VSCode syntax highlighter

### ISSUE THREAD

**Issue by mhemrg** [pedronauck/docz#23]
## Question

**Description**
How can I enable syntax highlighting for `.mdx` files in VSCode?

**Comment by Swapnull** [comment]
Hey @mhemrg, 

It doesn't look like there is a language extension for this yet. You could either set MDX files to get picked up as markdown or jsx files for partial highlighting of that flavour or create a VSCode language extension https://code.visualstudio.com/docs/extensionAPI/language-support.

**Comment by mrmartineau** [comment]
@mhemrg I added the below snippet to my VS Code settings so that it uses the markdown language syntax highlighting, this doesn't work properly because the "React" bits are not highlighted properly, but at least it's much better.

```
"files.associations": {
  "*.mdx": "markdown"
}
```

**Comment by TimPetricola** [comment]
There is an open issue on `mdx` repo for that: https://github.com/mdx-js/mdx/issues/119

**Comment by pedronauck** [comment]
I want a lot this too, will be so nice 🙏

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/roadmap/p/vscode-syntax-highlighting)

**Comment by nikolasburk** [comment]
Just found [this](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx) extension by [Matija Marohnić](https://twitter.com/silvenon) 👍
