### ISSUE TITLE
Why the packages are not on separate git repos ?

### ISSUE THREAD

**Issue by glinford** [pedronauck/docz#233]
## Question
Why the packages are not on separate git repos ?

**Description**
Docz publishes 5 packages to NPM
https://www.npmjs.com/package/docz?activeTab=dependencies
https://www.npmjs.com/package/docz-core?activeTab=dependencies
https://www.npmjs.com/package/docz-theme-default?activeTab=dependencies
https://www.npmjs.com/package/rehype-docz?activeTab=dependencies
https://www.npmjs.com/package/remark-docz?activeTab=dependencies

Those 5 packages are nested in the /packages folder.
For maintainability and ease of CR/PR/Updates would it make more sense to separate those 5 folders in 5 different git repos corresponding to there NPM package name ?

Also, it seems there is a circular dependency between docz and docz-theme-default
docz require docz-theme-default and docz-theme-default require docz which is also a bit weird in my opinion ...

**Comment by glinford** [comment]
@ematipico It's just seems to be an overkill to fork the whole docz just to customize one package inside it.

**Comment by ematipico** [comment]
Yes, in this case it is an overkill :cry:

**Comment by pedronauck** [comment]
Work in a monorepo is so much better to build, decoupling and test things. When you have separated packages you need most frequently to publish versions or link using `npm` and in a monorepo you just have your dependencies linked without any workaround. When you have a complex project, split it into packages with different concerns is better and I really think that isn't an overkill since install and fork the project is something really simple. You can see jest, react, create-react-app, babel and a lot of other projects doing the same thing!
