### ISSUE TITLE
Using default theme components in custom theme

### ISSUE THREAD

**Issue by tadeuszwojcik** [pedronauck/docz#283]
## Question
How to use some of the default theme components in custom theme?
**Description**
Hi,
I'd like to develop custom theme, but actually not whole from scratch, but only some of the components (like headers etc), for stuff like playground/codemirror editor I'd like to piggy back on default-theme, is that possible right now?

Love this lib btw, much much nicer to use & extend than styleguidist, and TS props table works after last update :)

**Comment by zephraph** [comment]
I ran across this too. I _think_ all that's required is to have the components be exported from the theme.

**Comment by zephraph** [comment]
I've been experimenting w/ the above, but it's not quite that straight forward.

**Comment by pedronauck** [comment]
HI @tadeuszwojcik, I know that this is a problem, but we're already working on a solution for this. We'll release a package called `docz-ui`, that will have a lot of components to help you to build your custom theme (eg. our playground, custom menus, etc).

But, this might take a while. So, in the next week I'll to try just to split our core components and create like the initial version of `docz-ui` :v:

**Comment by pedronauck** [comment]
This feature is already on our roadmap, please give us some vote there :pray:

### [📦&nbsp; New package docz-ui](http://roadmap.docz.site/roadmap/p/new-package-docz-ui)

**Comment by AryanJ-NYC** [comment]
Hey @pedronauck. First off, thanks for all your work. This library is awesome.

I need to customize the `Sidebar` `Content` component to use `position:static` instead of `position: fixed` since that breaks the UI of a [website WIP](https://5cc21b582462980008c3ca8b--frosty-einstein-280f98.netlify.com/examples). You'll see there that changing the content to `position: static` will fix it.

Are there any updates on the `docz-ui` package?
