### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by Haroenv** [pedronauck/docz#32]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Some documentation is long and complicated to find things in, which leads to lots of clicking around and reading

**Describe the solution you'd like**
Having a search dropdown, like on the [react documentation](https://reactjs.org), for example. This can be done using [DocSearch](https://community.algolia.com/docsearch/) for free, simply by having the autocomplete etc. as an option, and then explaining how to apply. A similar process as for [docusaurus](https://docusaurus.io) can be followed 

Note that I work for Algolia.

**Comment by pedronauck** [comment]
I really like this idea and it's in the roadmap, as soon as possible I'll create this on `docz-theme-default` 🙏

**Comment by Haroenv** [comment]
If there's anything we can do to help, ping :)

**Comment by pedronauck** [comment]
Thanks @Haroenv, pr are welcome too ✌️

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/roadmap/p/add-search-engine)

**Comment by Haroenv** [comment]
All right, makes sense!

**Comment by pedronauck** [comment]
## Released in the new [v0.5.0](https://github.com/pedronauck/docz/releases/tag/v0.5.0) 🚀

**Comment by Haroenv** [comment]
Any reason you chose not to go for Algolia?

**Comment by pedronauck** [comment]
@Haroenv, I've chosen for something faster to develop and less complex for now, but I'll improve this later...
