### ISSUE TITLE
PropsTable popover gets cut off by the top of the component

### ISSUE THREAD

**Issue by brmscheiner** [pedronauck/docz#332]
## Bug Report

**Describe the bug**

PropsTable popover gets cut off by the top of the component

**To Reproduce**

Add an enum prop with a lot of options to one of the first proptypes in a component. Show the `PropsTable` of that component. For example:

```
Button.propTypes = {
  variant: PropTypes.oneOf([
    'default',
    'link',
    'primary',
    'secondary',
    'danger',
    'pagination',
    'textSecondary',
    'textPrimary',
    'icon',
    'iconPrimary',
    'iconNeutral',
    'light',
  ])
}
```

**Environment**
Chrome 68.0.3440.106 (Official Build) (64-bit)

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/9775178/45451387-c797e800-b68f-11e8-9df1-563dc0d28775.png)

**Comment by marceloavf** [comment]
I can fix it at desktop, but the problem goes deeper in responsive.

- The tooltip is not responsive.
- The tooltip need to be outside the table, it need to float in another div and get element location with javascript, since it's a responsive table.

> The overflow table element breaks the component inside, it can be disabled in desktop resolutions with no side effect.

For this I think we have two solutions @pedronauck :

1. Change the tooltip component or
2. Create a "modal" when click in `Enum` on responsive resolutions, disabling the tooltip on that.

---

Example of the problem: 

The component fixed on desktop without changing the responsive overflow.

![01](https://user-images.githubusercontent.com/5435657/45587257-f43f4000-b8d9-11e8-8222-fc6045f4faa6.gif)

The component fixed on desktop and mobile, but breaking the table.

![02](https://user-images.githubusercontent.com/5435657/45587247-cbb74600-b8d9-11e8-8b5e-795ed604788a.gif)

**Comment by charzy** [comment]
I just had a look, I'm very surprised that `overflow-x` on the table is affecting the vertical overflow for the tooltip!

**Comment by pedronauck** [comment]
Closed in favor of the newest release.
