### ISSUE TITLE
Read name from package.json and populate title by default

### ISSUE THREAD

**Issue by albinekb** [pedronauck/docz#34]
## Feature Request

It would be nice if the "MyDoc" title defaulted to the `name` property inside package.json

**Describe the solution you'd like**

Read package.json name and populate title

**Describe alternatives you've considered**

Maybe creating a theme that does this? 🤔 

**Teachability, Documentation, Adoption, Migration Strategy**

the config file and other ways to set the title should overwrite this, reading name from package.json should probably only be done if there's no `title` configured. This would make it more zero-config than it is right now.

**Comment by pedronauck** [comment]
Good point @albinekb, I'm thinking about that, but we would need to humanize the app name from `package.json` and not sure it is a good choice 🤔

**Comment by vinyguedess** [comment]
maybe an "camelcasefy" on package name  @pedronauck ?

**Comment by albinekb** [comment]
Maybe we could send the whole package.json to the theme in some way, maybe a helper to fetch it in some way. If we could do that themes could use data from package.json to display version, name (with or without humanise), pick up [`repository`](https://github.com/LinusU/scandium/blob/master/package.json#L5) etc

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/roadmap/p/read-name-from-packagejson-and-populate-title)

**Comment by pedronauck** [comment]
## Released in the new [v0.5.0](https://github.com/pedronauck/docz/releases/tag/v0.5.0) 🚀
