### ISSUE TITLE
Support relative base

### ISSUE THREAD

**Issue by kentcdodds** [pedronauck/docz#352]
The default base is `/` which yields scripts like `/static/js/runtime~app.eee318d50257dca03656.js`. If I set the `base` to `''`, the script is still `/static/js/runtime~app.eee318d50257dca03656.js` (no change). I'm going to be publishing this to enterprise github pages (hosted at a URL like this one: `https://github.paypal.com/pages/kdodds/paypal-scripts/`), so all assets need to be relative to the `index.html` rather than absolute.

**Comment by nicholasess** [comment]
@kentcdodds you can set in doczrc the hashRouter and base.

See the file and the link of github page in website session from repository.

 https://github.com/nicholasess/react-native-share/blob/master/doczrc.js

**Comment by kentcdodds** [comment]
Oh right, duh. Thanks!

**Comment by kachkaev** [comment]
The `react-native-share` example above hard-codes root path at build time. This means that static artifacts can be only deployed in a certain location within a server, otherwise, links to `/static/(img|js)` don't work. I guess I managed to solve this issue by setting `base` to `"./"` – the resulting artifacts seem to work regardless of the path they are deployed to!

```diff
 export default {
   // ...
   hashRouter: true,
-  base: "/${libName}/",
+  base: "./",
 };
```

Hope this escape hatch keeps working in future versions of docz!

**Comment by iaincollins** [comment]
Would also like to see explicit support for relative paths.

It seems odd it's not the default behaviour - using './' as base path isn't the same.

For anyone coming to this, 'hashRouter' was removed, and it doesn't appear there is anyway to do relative path support in docz currently.
