### ISSUE TITLE
React.Children child.type different behaviour

### ISSUE THREAD

**Issue by ptdede** [pedronauck/docz#382]
## I Have a Question

I Have some components. Let say comp A and B. 
Inside A, i want to pass down some props to B if B is direct children of A.
example:

```
<A>
   <B />
</A>
```

i am using this code inside Component A:
```
    const filterChild = React.Children.map(children, (child: React.ReactElement<any>) => {
        if (child.type === B) {
            return React.cloneElement(child, {
                gap: this.state.gap,
            });
        } else {
            return null;
        }
    });
    return <StyledA>{filterChild}</StyledA>;
```

When i run my React program, it's working as expected. `<B>` is rendered inside `<A>`
but when i use docz, it unable to render `<B>` because ` child.type === B ` statement is false.

Is compound component is not supported?

**Expected behavior**

Using same component output same result.

**Environment**

* OS: OSX High Sierra
* Node/npm version: Node 8.12.0 / npm 6.4.1

**Additional context/Screenshots**
in React
<img width="578" alt="screen shot 2018-10-02 at 13 16 15" src="https://user-images.githubusercontent.com/3388701/46330433-81f28d80-c645-11e8-9e10-4d90f993042e.png">

in mdx
<img width="565" alt="screen shot 2018-10-02 at 13 17 01" src="https://user-images.githubusercontent.com/3388701/46330452-9040a980-c645-11e8-8af6-7637251895c5.png">

**Comment by wsmd** [comment]
Hi @ptdede, I believe this issue you are running into is due the nature of the react-hot-reloader (let's refer to it as RHL), which Docz uses under the hood, not so much an issue of docz itself. 

The RHL wraps each component in a proxy component, `ProxyComponent`.

In your example above,`child.type` (when running under RHR, that is within Docz) returns a reference to the proxy component, not the original class itself. Therefore, `child.type` is not the same as `B`.

Think of it this way: `ProxyComponent(B) === B`. This equation is not true.

RHL is kind enough to transfer static properties from the original component to the proxied one. We can leverage that as a workaround/alternative.

A common practice is to use a static property (let's call it `role` for example) that can be used to achieve the same purpose. Not only that, but it's purpose is intentional and explicit, which is a plus.

```jsx
// ComponentA

export const ComponentA = props => {
  const filterChild = Children.map(props.children, child => {
    // although child.type is a proxy, statics will still be available
    // therefore we can check for the role property that we explicitly set
    if (child.type.role === ComponentB.role) {
      return cloneElement(child, {/* child props */});
    } else {
      return null;
    }
  });
  return <div>{filterChild}</div>;
}

// ComponentB

export const ComponentB = ({ children, secret }) => (
  <div>The secret is: {secret}</div>
);

ComponentB.role = 'B'; // ←
```

**Comment by ptdede** [comment]
Hi @wsmd ! That's crystal clear. So, i have to create static property inside all of my components would resolve my problem.. Great idea, for now i'm doing it.. Thanks for the great answer and explanation 👍
