### ISSUE TITLE
Display Typescript enums in PropsTable

### ISSUE THREAD

**Issue by henrykuzmick** [pedronauck/docz#408]
Hey! Thanks for this package, it's damn awesome!

I'm not quite sure if this is a bug or a feature request, but here goes:
When using Typescript and defining an enum prop like this:
```
type Props = {
  tag: 'h1' | 'h2' | 'h3' | 'p' | 'span';
}
```

I can then use PropsTable and see `enum` as a result. This allows me to hover and see possible inputs.
This is awesome, but it kind of breaks when I define a props like this:

```
type Tag = 'h1' | 'h2' | 'h3' | 'p' | 'span';
type Props = {
  tag: Tag
}
```

In this case the props table just says `Tag`. 
It would be great if I could hover over it and see the possible values, just like in the first case.

Thanks!

**Comment by pedronauck** [comment]
Yeah, this is another bug around react-docgen 😕I'll close this issue in favor of #240 that contain all this bugs on it :v:

**Comment by NasraMohammad** [comment]
Hi, we were wondering if this is possible yet, or is it due to this bug?
We have looked into issue #240, but we're not sure if this has been closed or not as still seeing it, and thought it most relevant to post here as same use case.
Thanks
https://stackoverflow.com/questions/56515660/docz-how-to-render-typescript-definitions-other-than-interfaces-as-props
