### ISSUE TITLE
Direct support for componentsMap in doczrc?

### ISSUE THREAD

**Issue by chrisrzhou** [pedronauck/docz#472]
Hi I am currently trying to extend the default theme using my own custom componentsMap. I noticed that this is only possible by creating a custom theme.  Given that the default theme is really well written and organized, is it possible to expose configuring componentsMap directly in the doczrc file?  Currently we need to write a whole theme from scratch.

Thanks and if this is possible and a reasonable request and approach, I would be willing to help dig more into implementing it!

#question

**Comment by pedronauck** [comment]
That's a pretty good idea, I think that is totally possible, I'll try to do this and release in the next version :)

**Comment by pedronauck** [comment]
This isn't possible yet since we cannot pass a function in the configuration object. I need to think about how we can change our architecture to accept methods in `doczrc`, but for now I isn't possible, but still keeping an awesome idea. Please, add your suggestion on our roadmap 🙏 

http://feedback.docz.site
