### ISSUE TITLE
CSS / position fixed elements

### ISSUE THREAD

**Issue by yyynnn** [pedronauck/docz#474]
So fixed position elements go out of the playground element / out of flow.

![image](https://user-images.githubusercontent.com/13677727/49001952-381eb300-f16f-11e8-9d6e-1f517f2912f1.png)

One way is to pass additional prop like: `position="relative"`, to contain it. But this is kinda stupid. 
Another way mb is to parse components for 'position: fixed' and override it.
Or just use some ccs hacks like '-webkit-transform: translateZ(0);' + need to calculate height of child.
or use an iframe.

**Comment by pedronauck** [comment]
Fixed on [v0.12.14](https://github.com/pedronauck/docz/releases/tag/v0.12.14) ✅

**Comment by weslleyaraujo** [comment]
I think `position: "relative"` in the wrapper will not help in this case 😔

Currently I am having an issue with a `position: fixed` element, and since fixed elements will always be positioned as its ancestor containing block (which I believe is the <body /> in this case)
it renders outside of the component preview:

![screen shot 2018-12-10 at 10 53 34](https://user-images.githubusercontent.com/2286385/49740878-8070c180-fc95-11e8-81ca-2cbbc073413e.png)

There are tricks using `translate` as mentioned above, but I think still would tricky since it may need some calculation of its children elements. A similar discussion happened on [Styleguidist](https://github.com/styleguidist/react-styleguidist/issues/930).

One solution (as done by Storybook) is to render the elements inside an iframe, which would also help making sure no styles from docz conflicts with the component itself... I am pretty sure there are a lot of tradeoffs as well tho 😅

**Comment by mattfelten** [comment]
I'm also experiencing this issue. [Catalog](https://github.com/interactivethings/catalog/) has an `iframe` prop on their version of the playground so that `position: fixed` elements don't overlay on the site, but within the playground only.

**Comment by pedronauck** [comment]
Landed on [v0.12.16](https://github.com/pedronauck/docz/releases/tag/v0.12.16)
