### ISSUE TITLE
Blog support

### ISSUE THREAD

**Issue by arslivinski** [pedronauck/docz#55]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
A blog engine, alongside the documentation. I think that this would be an awesome addition. One tool to rule them all.

**Describe alternatives you've considered**
I think that https://docusaurus.io is a nice example of doc engine with blog support.

**Teachability, Documentation, Adoption, Migration Strategy**
Use MDX to write blog posts about the new features of the documented tool.

**Comment by marceloavf** [comment]
Another adition to this `new features` of the documented tool should be an update section like `electricjs` does here https://electricjs.com/updates/

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/roadmap/p/blog-support)
