### ISSUE TITLE
Support env files to set configuration

### ISSUE THREAD

**Issue by edwilliams** [pedronauck/docz#61]
## Bug Report

**Incorrect path**

*Docz is looking in the wrong place for the my components imported modules. I think it is not taking into account `NODE_PATH=src` in my `.env` file*

**To Reproduce**

1. Use Create React App boilerplate
2. Save `NODE_PATH=src` into an `.env` file
3. Import modules into component without `src` in the path (e.g. `import Foo from 'lib/foo'` rather than `import Foo from 'src/lib/foo'`)
4. See error below

```shell
These dependencies were not found:

* lib/foo in ./src/components/Partials/SubTitle/index.js

To install them, you can run: npm install --save lib/foo
```

**Environment**

* OS: OSX 10.13.3
* Node: v8.9.4
* NPM: v6.0.1

**Comment by pedronauck** [comment]
sorry @edwilliams, but we're not supporting `.env` files yet, this is a roadmap feature but not implemented so far... what you can do is set your `src` in the `doczrc.js` file:

```js
export default {
  src: process.env.NODE_PATH || 'whatever/path/you/want'
}
```

**Comment by edwilliams** [comment]
thanks @pedronauck, work fine now

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/admin/board/roadmap/p/support-env-files-to-set-configuration)
