### ISSUE TITLE
error in websocket connection

### ISSUE THREAD

**Issue by xiaofan2406** [pedronauck/docz#640]
## Question

**Description**

I am getting the browser console error when running the dev process:

```
WebSocket connection to 'ws://127.0.0.1:60505/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

This is probably because I have my `host` configured to something like `192.167.1.88` (which is my vm IP address, and I am opening my browser in my host machine).

Question: 
- What is the web socket for? hot-reload? (the hot reload works fine with the error)
- Am I able to configure the websocket host so I don't get the error any more?

Version:
I am on the latest version `0.13.7`

**Comment by jochienabuurs** [comment]
You can configure the websocket host (and port) by passing it as arguments to the run script (i'm using yarn):

```
yarn docz dev --websocketHost=192.167.1.88 --websocketPort=3000
```

Or you can create a doczrc.js file and add it there:
```
export default {
    host: '0.0.0.0',
    port: 9001,
    websocketHost='192.167.1.88',
    websocketPort: 9002,
}
```

I found it out when trying to run concurrent docz apps. Because the websocket port is already in use, you can only run one instance of the app. Too bad these configs aren't in the docs...

**Comment by xiaofan2406** [comment]
I actually tried the doczrc file config. but it didnt work for me somehow.

but will give the cli args a try

**Comment by jochienabuurs** [comment]
The doczrc file should work too. I'm actually using it myself ...

**Comment by xiaofan2406** [comment]
on the second try, both methods work. 

thanks for your help.
