### ISSUE TITLE
Translating PropsTable

### ISSUE THREAD

**Issue by mhemrg** [pedronauck/docz#66]
## Feature Request

I want to localize `PropsTable` and translate it. I think this feature is not implemented yet.

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/admin/board/roadmap/p/translating-propstable)
