### ISSUE TITLE
Execute JS

### ISSUE THREAD

**Issue by bichotll** [pedronauck/docz#67]
## Feature Request

It would be cool if I had the possibility to run also JS, not just JSX. I suppose that will be a plugin maybe?

I'm also developing a JS library and I thought it would be cool to use this project to document part of it.

A clear alternative would be the use of a plugin.

I suppose you already had that in mind. In any case, here I leave it 😅👍

**Comment by pedronauck** [comment]
For sure @bichotll, we have a feature no our roadmap to integrates something like `<PropsTable>` but using JSDocs to document js code, will be awesome, keep looking into docz, great news are coming soon! :v:

**Comment by bichotll** [comment]
Oh man! That sounds awesome! :)

Thanks for the project...and the effort!

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/admin/board/roadmap/p/integration-with-jsdocs)
