### ISSUE TITLE
yarn packages fail (following contributing guidelines)

### ISSUE THREAD

**Issue by ivan-dalmet** [pedronauck/docz#706]
Trying to contribute on the 1.0.0-rc.3 but following the contributing guidelines doesn't work :(
```
yarn
yarn bs
yarn packages --> fail 😢
``` 
Node version: v10.13.0
Yarn version: 1.15.2

**Comment by pedronauck** [comment]
Can you show me the error @ivan-dalmet ?

**Comment by ivan-dalmet** [comment]
![image](https://user-images.githubusercontent.com/9749061/54838118-2639c080-4cc8-11e9-985c-3f63e7c28a19.png)

**Comment by ivan-dalmet** [comment]
![image](https://user-images.githubusercontent.com/9749061/54838169-40739e80-4cc8-11e9-806d-52a295792891.png)

**Comment by ivan-dalmet** [comment]
It's a fresh new fork (I removed my old one and started from scratch)

**Comment by ivan-dalmet** [comment]
The problem comes from the snapshots

**Comment by Glazy** [comment]
Thanks for filing an issue about this @ivan-dalmet.

I also just experienced this whilst working on the project. The snapshot tests will fail for everyone because the absolute path to an example fixture is stored in the snapshot.

Unless us users are storing `docz` at the exact same location in our filesystem as @pedronauck then the snapshots will always fail for us. You can work around this by running `yarn test -u` in `other-packages/babel-plugin-export-metadata` but make sure you don't commit the updated snapshot with any changes you make 💪

**Comment by macklinu** [comment]
I wonder if there's a way to strip out the part of the file path for the tests so that tests can pass on everyone's machine - taking a look to see if I can help out with this.

**Comment by pedronauck** [comment]
Oh, my bad 🤔 Thanks @Glazy, I'll check if I can help with this. It's a so much important thing!

**Comment by macklinu** [comment]
I did take a look at the test but was unable to come up with a solution (thanks @pedronauck for commenting to remind me to follow up 😂).

**Comment by pedronauck** [comment]
Fixed, will be release today :)
