### ISSUE TITLE
Auto generation of component's prop variants

### ISSUE THREAD

**Issue by prarthana-s** [pedronauck/docz#77]
## Feature Request

This will be a very helpful feature: Props are evaluated, and components are auto generated for some/all possible combinations in the Playground. 

An alternative suggestion is to consider each prop, and generate components for each of its possible values while keeping the other prop values fixed.

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

We think that is better **keep Github issues only for bugs** and other issues! 🐞
This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/admin/board/roadmap/p/auto-generation-of-components-prop-variants)
