### ISSUE TITLE
Props components not working if JS not close to MDX in 1.0.0-rc.8

### ISSUE THREAD

**Issue by ivan-dalmet** [pedronauck/docz#776]
## Bug Report

If the JS/JSX file of the component is not in the same folder as the MDX file, it's not working in 1.0.0-rc.8 (working in 1.0.0-rc.7)

@pedronauck I think it's linked to this commit: https://github.com/pedronauck/docz/commit/c7c7bc796727a10ab5435b8f2c9d0e185bf2b142

**Example:**
https://github.com/ivan-dalmet/docz-issue-sandbox/tree/master/issue-776

**Comment by rfoel** [comment]
You have a typo [here](https://github.com/ivan-dalmet/docz-issue-sandbox/blame/master/issue-776/ko/src/button.mdx#L6).

```
import Button from './Components/Button'
```

Your components folder is lowercase and you're trying to import it with uppercase.

The reason it renders the Button component is because React is not case-sensitive for paths maybe and Docz is?

**Comment by ivan-dalmet** [comment]
Erf that right @rfoel :/
The example is wrong ><'
But there still is a problem with rc8 in our project which doesn't render Props anymore.
I'm closing that issue and we will try to reproduce the bug.

**Comment by rfoel** [comment]
@ivan-dalmet are you importing your props for your components? Maybe it's related to [this](https://github.com/pedronauck/docz/issues/240#issuecomment-480016915).

**Comment by ivan-dalmet** [comment]
@rfoel I close this issue and open a new one --> https://github.com/pedronauck/docz/issues/777
