### ISSUE TITLE
Allow users to edit the playground examples

### ISSUE THREAD

**Issue by fzaninotto** [pedronauck/docz#79]
## Feature Request

The playground doesn't really allow to play. In order to fully discover a component, users like to manipulate them themselves. 

**Possible solutions**

- Make code editable in playground (but watch out for errors)
- Add editable "knobs" to playground (see [storybook knobs addon](https://github.com/storybooks/storybook/tree/master/addons/knobs))

**Comment by pedronauck** [comment]
I'm thinking of creating something like knobs on `<Playground>`. Maybe something like that:

```js
import { Playground } from 'docz'

<Playground knobs={{ name: 'text' }}>
  {({ values }) => (
    <Button onClick={() => console.log(values.name)}>
      Click me
    </Button>
  )}
</Playground>
```

This is simple and doesn't need any dependency, just a simple schema! The point here is how to attach behaviors on playground without coupling styles and get it flexible!

About make code editable, is another thing that I have some doubts!

**Comment by fzaninotto** [comment]
great solution, looking forward to it!

**Comment by fzaninotto** [comment]
As for making the playground code editable, maybe [klipse](https://github.com/viebel/klipse) is a good solution?

**Comment by pedronauck** [comment]
Great choice @fzaninotto

**Comment by pedronauck** [comment]
To facilitate user feedbacks and make a really good roadmap, now we're using [Canny](https://canny.io) as a tool to create our roadmap 😍

This issue is already on our roadmap, so I'll close this issue in favor of it!

### 👉🏻 [Check this issue on roadmap](https://docz.canny.io/admin/board/roadmap/p/allow-users-to-edit-the-playground-examples)

**Comment by albinekb** [comment]
I think https://github.com/Microsoft/monaco-editor would be a nice editor to include.

**Comment by pedronauck** [comment]
Thanks to the tip @albinekb. Just to know, do you think that isn't a good thing have the roadmap on canny instead of github?

**Comment by fzaninotto** [comment]
I personally prefer GitHub. I don't want to open a new tool to see the roadmap, and I don't want to register to a new service just to do a 👍

**Comment by albinekb** [comment]
I prefer github too, then everyone can be here and comment, add interesting ideas and see what's already voted for, also you can subscribe to the issues and help with implementing things a lot better. You can see how we used github projects to track stuff in Kap https://github.com/wulkano/kap/projects/2

**Comment by pedronauck** [comment]
I agree with the issue of decentralization, but I find Github very limited as a roadmap tool. What was happening here is that issues were being inflated by the number of enhancements, it's very bad to manage that and this gives a sense of "project with many issues" to anyone who looks at the project for the first time.

> Also it feels less open source/inclusive with roadmap/new features in canny.

This can be something bad, really. But how I told, I don't think that Github is a good roadmap tool, do you have maybe other tip or idea about that?

**Comment by albinekb** [comment]
I don't think it's too bad, look at how we're doing it in kap: https://github.com/wulkano/kap/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
With the roadmap in github projects: https://github.com/wulkano/kap/projects/2

**Comment by pedronauck** [comment]
For sure, that's what we were doing at all. But this makes a non-real sense of many issues to solve for me, and I think that's is bad. Because every time that I need to see how many issues I have to fix I need to filter all issues, out of this things end up mingling. When I saw the board on Canny, I can see what people want instantly.

Assuming that I have ten feature requests here on Github, If I see what is the most voted I would need to enter in one by one and count all votes manually, this is so bad. I don't have time for that, unfortunately, I have a full-time job and I need to be quick when I doing things for docz 😕 

I don't talk that I can't do what I do in Canny, the point here is that there's better than here to keep a concise roadmap.

**Comment by albinekb** [comment]
> would need to enter in one by one and count all votes manually, this is so bad

You can sort on reactions:
https://github.com/divadoab/service-sync/pull/17/files

I'm not interested in learning how canny works, I think it's really messy over there (as a github user, I feel lost), I would pick up issues here in github and help implement stuff, but when it's in canny it feels to disconnected and more effort required. But it's your project and I wish you the best for it going forward 🎉 Just my 5c is, I think it's more familiar and easier for users to navigate features in github rather than an external service 👍

**Comment by pedronauck** [comment]
I really appreciate your help @albinekb and the honest feedback, I don't think that docz is my project, at the moment that I gave it to the community I need to hear all people involved and to accomplish this goal that we made a partnership with Canny, because I think that I could have a more concise and clear feedback . So, we will try to keep both, making an official roadmap there, but all feature request that arises can be sent and discussed here in the first moment! What do you think about?

**Comment by albinekb** [comment]
Sounds great 🙌

**Comment by edygar** [comment]
Just a little addition to the discussion: I really liked [react-styleguidist](https://github.com/styleguidist/react-styleguidist) way of doing it: lazy loading the Editor (requires clicking on "VIEW SOURCE" button) and it has the live edit. I've tried to see if it was available as an external dependency but it looks like out it is very tied to the solution as a whole, unfortunately
