### ISSUE TITLE
docz failed to parse html tags in component

### ISSUE THREAD

**Issue by sixclones** [pedronauck/docz#947]
I have a component that render a `<header>` tag but when I launch docz I got this
```
ERROR in ./src/components/SiteHeader/index.js 5:2
Module parse failed: Unexpected token (5:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| const SiteHeader = () => (
>   <header>
|     <Link to="/">Accueil</Link>
|     <Link to="/projects">Projets</Link>
 @ ./docs/SiteHeader.mdx 18:0-54 68:79-89
 @ ./.docz/app/imports.js
 @ ./.docz/app/root.jsx
 @ ./.docz/app/index.jsx
 @ multi ./node_modules/docz-core/node_modules/react-dev-utils/webpackHotDevClient.js ./.docz/app/index.jsx
```

**Comment by zicodeng** [comment]
Can you provide us with your `doczrc.js` here, thanks!

**Comment by sixclones** [comment]
Here it is
```
export default {
  src: './docs/',
  files: '*.mdx',
  debug: true,
  ignore: ['node_modules/**/*.js']
};
```

**Comment by zicodeng** [comment]
@sixclones , sorry for the late reply, for some reasons, I didn't get any notifications for this thread. The problem is your config file `src`. If you look at the doc on the website, it says: `src: Define the source folder of your components. Only the files in this folder will be parsed. Every file out of this folder will not be found.`. It seems your source files are under `./src`, not `./docs`
