### ISSUE TITLE
Page not found /

### ISSUE THREAD

**Issue by coreybruyere** [pedronauck/docz#981]
## Question

**Description**
I'm trying to set up an existing TS project with docz. I have components inside of a Lerna monorepo, so they follow this pattern `packages/core/**/*.tsx`. Within the same component directory is the MDX file for docz. However, when running I'm sent to the general Gatsby 404 page which shows the list of pages. Am I just doing pathing wrong somewhere, do I need to change something in `docsrc.js`?

<img width="1093" alt="Screen Shot 2019-07-26 at 10 37 33 AM" src="https://user-images.githubusercontent.com/3430222/61970346-7041f400-af91-11e9-8204-3a3200aad04f.png">

* Twitter: If it's just a quick question you can ping me on Twitter: https://twitter.com/pedronauck

**Comment by homejames203** [comment]
I have a similar setup. A component library that I installed gatsby / gatsby-theme-docz / docz into. 

I had to make sure at least one of my .mdx files had a route set to '/'. 

```
---
name: My home page
route: /
menu: Overview
---
```

I do however still get some errors on initial run in development. They go away once i change/save any of my .mdx files because gatsby recompiles.

**Comment by coreybruyere** [comment]
@homejames203 Do I need to specify a home page? I currently only have MDX files in my component directories

**Comment by coreybruyere** [comment]
After setting route and resaving the file localhost pointed me to the correct location
